import { InMemoryDbService } from 'angular-in-memory-web-api';

export class InMemoryDataService implements InMemoryDbService {
  [x: string]: any ;

  createDb() {
    const employeeList = [
      {
        id: 1,
        name: 'John',
        designation: 'Senior UI Specialist',
        technologies: 'UI',
        skill: 'Angular',
        totalExperience: 7,
        availability: 3,
        baseLocation: 'Pune',
        openRelocate: 'Yes',
      },
      {
        id: 2,
        name: 'Marks Miller',
        designation: 'UI Specialist',
        technologies: 'VS,UI',
        skill: 'React Native',
        totalExperience: 2,
        availability: 3,
        baseLocation: 'Pune',
        openRelocate: 'Yes',
      },
      {
        id: 3,
        name: 'Robert Downey',
        designation: 'Senior UI Specialist',
        technologies: 'UI',
        skill: 'React',
        totalExperience: 3,
        availability: 3,
        baseLocation: 'Indore',
        openRelocate: 'Yes',
      },
      {
        id: 4,
        name: 'Tom Hanks',
        designation: 'Senior Lead UI Specialist',
        technologies: 'UI,VS',
        skill: 'Vue.js',
        totalExperience: 4,
        availability: 3,
        baseLocation: 'Mumbai',
        openRelocate: 'No',
      },
      {
        id: 5,
        name: 'Jackie Chan',
        designation: 'Associate UI Specialist',
        technologies: 'UX',
        skill: 'Figma',
        totalExperience: 10,
        availability: 3,
        baseLocation: 'Indore',
        openRelocate: 'Yes',
      },
      {
        id: 6,
        name: 'Kevin Spacey',
        designation: 'UI Specialist',
        technologies: 'VS,UX',
        skill: 'Figma,XD',
        totalExperience: 9,
        availability: 3,
        baseLocation: 'Pune',
        openRelocate: 'Yes',
      },
      {
        id: 7,
        name: 'Jenifer Parker',
        designation: 'Lead UI Specialist',
        technologies: 'UX,VS',
        skill: 'Angular',
        totalExperience: 7,
        availability: 3,
        baseLocation: 'Indore',
        openRelocate: 'Yes',
      },
      {
        id: 8,
        name: 'Denzel Washington',
        designation: 'UI Specialist',
        technologies: 'UI,VS',
        skill: 'Angular',
        totalExperience: 5,
        availability: 3,
        baseLocation: 'Pune',
        openRelocate: 'No',
      },
      {
        id: 9,
        name: 'Russell Crowe',
        designation: 'Senior UI Specialist',
        technologies: 'UI,UX,VS',
        skill: 'Angular,Figma',
        totalExperience: 3,
        availability: 3,
        baseLocation: 'Pune',
        openRelocate: 'No',
      },
      {
        id: 10,
        name: 'Thomas Hail',
        designation: 'UI Specialist',
        technologies: 'UI',
        skill: 'React',
        totalExperience: 13,
        availability: 3,
        baseLocation: 'Indore',
        openRelocate: 'Yes',
      },
      {
        id: 11,
        name: 'Jennitor Parkor',
        designation: 'UI Specialist',
        technologies: 'VS,UI',
        skill: 'React Native',
        totalExperience: 15,
        availability: 3,
        baseLocation: 'Pune',
        openRelocate: 'Yes',
      },
      {
        id: 12,
        name: 'Angelina Jolie',
        designation: 'Lead UI Specialist',
        technologies: 'UI,UX',
        skill: 'Angular',
        totalExperience: 9,
        availability: 3,
        baseLocation: 'Pune',
        openRelocate: 'Yes',
      },
      {
        id: 13,
        name: 'Leonardo DiCaprio',
        designation: 'UI Specialist',
        technologies: 'UI,UX,VS',
        skill: 'Angular,XD',
        totalExperience: 4,
        availability: 3,
        baseLocation: 'Mumbai',
        openRelocate: 'No',
      },
      {
        id: 14,
        name: 'Tom Cruise',
        designation: 'UI Specialist',
        technologies: 'UI,UX,VS',
        skill: 'Angular,Sketch,XD',
        totalExperience: 6,
        availability: 3,
        baseLocation: 'Hyderabad',
        openRelocate: 'Yes',
      },
      {
        id: 15,
        name: 'John Travolta',
        designation: 'Associate UI Specialist',
        technologies: 'UI,VS',
        skill: 'Angular',
        totalExperience: 8,
        availability: 3,
        baseLocation: 'Hyderabad',
        openRelocate: 'No',
      },
      {
        id: 16,
        name: 'Sylvester Stallone',
        designation: 'UI Specialist',
        technologies: 'UI,VS',
        skill: 'Angular',
        totalExperience: 5,
        availability: 3,
        baseLocation: 'Mumbai',
        openRelocate: 'Yes',
      },
      {
        id: 17,
        name: 'Kate Winslet',
        designation: 'Lead UI Specialist',
        technologies: 'UI,VS',
        skill: 'React',
        totalExperience: 2,
        availability: 3,
        baseLocation: 'Indore',
        openRelocate: 'Yes',
      },
      {
        id: 18,
        name: 'Charlize Theron',
        designation: 'Lead UI Specialist',
        technologies: 'UX,VS',
        skill: 'Figma,XD,Sketch',
        totalExperience: 5,
        availability: 3,
        baseLocation: 'Mumbai',
        openRelocate: 'No',
      },
      {
        id: 19,
        name: 'Keira Knightley',
        designation: 'UI Specialist',
        technologies: 'UI,VS',
        skill: 'Angular',
        totalExperience: 10,
        availability: 3,
        baseLocation: 'Pune',
        openRelocate: 'Yes',
      },
      {
        id: 20,
        name: 'Scarlett Johanssonton',
        designation: 'Associate UI Specialist',
        technologies: 'UI,VS',
        skill: 'Vue.js',
        totalExperience: 12,
        availability: 3,
        baseLocation: 'Pune',
        openRelocate: 'No',
      },
    ];
    return { employeeList };
  }
}
